/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdminHeader: typeof import('./components/AdminHeader.vue')['default']
    Badge: typeof import('./components/Badge.vue')['default']
    Button: typeof import('./components/Button.vue')['default']
    Combobox: typeof import('@headlessui/vue')['Combobox']
    ComboboxButton: typeof import('@headlessui/vue')['ComboboxButton']
    ComboboxInput: typeof import('@headlessui/vue')['ComboboxInput']
    ComboboxOption: typeof import('@headlessui/vue')['ComboboxOption']
    ComboboxOptions: typeof import('@headlessui/vue')['ComboboxOptions']
    Dialog: typeof import('@headlessui/vue')['Dialog']
    DialogPanel: typeof import('@headlessui/vue')['DialogPanel']
    DialogTitle: typeof import('@headlessui/vue')['DialogTitle']
    Header: typeof import('./components/Header.vue')['default']
    Loader: typeof import('./components/Loader.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./components/Select.vue')['default']
    TextInput: typeof import('./components/TextInput.vue')['default']
    Toast: typeof import('./components/Toast.vue')['default']
    TransitionChild: typeof import('@headlessui/vue')['TransitionChild']
    TransitionRoot: typeof import('@headlessui/vue')['TransitionRoot']
  }
}
